version: '3.7'

services:
  postgres:
    image: postgres:alpine
    container_name: restbase-db
    volumes:
      - ./data/postgres_db:/var/lib/postgresql/data/
    env_file:
      - ./.envs/.env.postgres
    ports:
      - 5432:5432

  redis:
    image: redis:alpine
    container_name: restbase-redis

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: restbase-backend
    ports:
      - 8000:8000
    volumes:
      - ./app/:/code/app
      - ./scripts/:/code/scripts
    env_file:
      - ./.envs/.env.app
      - ./.envs/.env.postgres
